### PR TITLE
add new types: panos_decryption_policy_rule, panos_application_group, panos_custom_url_category, and panos_profiles_url_filtering

### PR DESCRIPTION
**Pull request by gbrusick**
added new types for personal use:
panos_decryption_policy_rule, 
panos_application_group, 
panos_custom_url_category, 
panos_profiles_url_filtering

### CODE REVIEW

**Comment by DavidS** [comment]
Hi @gbrusick ,

thanks a lot for this contribution. Most of the rubocop warnings can be fixed by running `pdk validate -a` or `bundle exec rubocop -a` (depending on your local setup). Feel free to reach out with any questions you have, we're here to help you get this over the line.

Cheers, David

**Comment by gbrusick** [comment]
I understand I'm missing unit tests. I still need to add them.
I tested the 4 types on real devices, but I won't be able to do the acceptance test due tu ruby version not being recent enough on my agent.

**Comment by DavidS** [comment]
No worries, we can check the acceptance tests on our infrastructure.

**Comment by da-ar** [comment]
> I added unit tests for the four types and providers
> It's my first attempts at coding ruby, so I really don't know what is wrong with these two lines

Hey @gbrusick those were linting errors from rubocop. While it can fix many issues, some you just need to know how to handle (but you do get guidance from the error https://travis-ci.com/puppetlabs/puppetlabs-panos/jobs/240391462#L940) . You can take a look at the commit I pushed to see what changed.

**Comment by gbrusick** [comment]
OK, now all has passed. panos_custom_url_category is also compatible with new type field in 9.0 panso

**Comment by da-ar** [comment]
@gbrusick things are looking good. In order to acceptance test on our infrastructure, could you add at least one example for each new type to `spec/fixtures/create.pp`, `spec/fixtures/update.pp` and `spec/fixtures/delete.pp` that demonstrates how they can be used. If you look at the examples in each file you should get an idea about what is required. 

If you have any difficulty, let us know and we'll do what we can to get this merged.

**Comment by gbrusick** [comment]
I added examples that I took from production devices and modified the names, but I cannot run the acceptance, because the server that has access to the devices doesn't have a version of rubby recent enough. Could you please run it and tell me if there is something wrong.

**Comment by sanfrancrisko** [comment]
Thank you @gbrusick for your PR. There does not seem to have been any activity on this PR for 90 days, therefore it will be closed. Please feel free to reopen again in the future and we will be happy to assist in any way we can.

Thanks!
Puppet IAC Team

**Pull request closed without merging**
